### ISSUE TITLE
Action signs blank by default?

### ISSUE THREAD

**Issue by ulrikpedersen** [gilesknap/mciwb#78] opened 2023-03-12 20:54 UTC
The action signs don’t have the action written on the sign - so when placing one it pops up a screen where you can then type in “select” for example. The function does work but in the demo video it seems the action command is already written on the sign so placing it is much quicker because it doesn’t require typing each time… Bug 🐞 or feature? 😄

**Comment by gilesknap** [comment] 2023-03-12 23:20
that's a big for sure.

it should work because the CI tests it!

I'll take a look tomorrow.

**Comment by compX44** [comment] 2023-03-13 02:14
Hello. I am experiencing the same issue with the signs and I can't see the sand blocks being added when I followed the instructions.

**Comment by gilesknap** [comment] 2023-03-13 08:21
@compX44 @ulrikpedersen I just had a go at reproducing this and failed to do so.

@compX44 which OS are you using please? (I'm on Linux and Ulrik is on Mac)

One other difference for me is I'm running against a remote Minecraft server and that is because my docker installation on my workstation is broken. I'll get it fixed and try mciwb's own minecraft server to see if that is where the issue lies.

**Comment by gilesknap** [comment] 2023-03-13 08:45
I've now got a fresh server working using 
```
mciwb start
```

It still does not show the issue that you both are seeing. 

We need to work out what is different between our setups.

**Comment by gilesknap** [comment] 2023-03-13 21:47
@ulrikpedersen @compX44 please can you try this:
In the game type `/clear` to remove all items from inventory.
Then report the output of the following commands in mciwb ipython :
```python
world.signs.give_signs()
world.player.inventory()
```

It should look somthing like this:
```
Out[3]: 'TransformerScorn has the following entity data: [{Slot: 0b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"select"}\'}, display: {Name: \'{"text":"select"}\'}}}, {Slot: 1b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"paste"}\'}, display: {Name: \'{"text":"paste"}\'}}}, {Slot: 2b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"expand"}\'}, display: {Name: \'{"text":"expand"}\'}}}, {Slot: 3b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"clear"}\'}, display: {Name: \'{"text":"clear"}\'}}}]'
```

**Comment by gilesknap** [comment] 2023-03-13 21:48
@ulrikpedersen I'm not sure if the chown issues are benign or not - will look at this (having all sorts of issues with podman/docker differences and this is related )

**Comment by gilesknap** [comment] 2023-03-13 21:52
@compX44 your symptoms of not being able to break blocks is weird. I thought maybe you were in adventure mode.

Tomorrow I'll switch over to Windows and see if I can reproduce any of these issues. I at least have a working docker on my windows system!

**Comment by ulrikpedersen** [comment] 2023-03-13 22:19
> In the game type /clear to remove all items from inventory.

This just gives me an error 🤔 

```
Unknown or incomplete command, see below for error
clear<--[HERE]
```
(so I threw away the signs with the `q` instead)

> Then report the output of the following commands in mciwb ipython :

```
In [4]: world.signs.give_signs()

In [5]: world.player.inventory
Out[5]: 'AlbaDancer has the following entity data: [{Slot: 0b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"select"}\'}, display: {Name: \'{"text":"select"}\'}}}, {Slot: 1b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"paste"}\'}, display: {Name: \'{"text":"paste"}\'}}}, {Slot: 2b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"expand"}\'}, display: {Name: \'{"text":"expand"}\'}}}, {Slot: 3b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"clear"}\'}, display: {Name: \'{"text":"clear"}\'}}}]'
```

> I'm not sure if the chown issues are benign or not - will look at this (having all sorts of issues with podman/docker differences and this is related )

I think I had a bit of a mess. I had tried to also run up your docker image - don't know if that had something to do with it(?) In any case, I deleted the `mciwb-server` folder and started over. That seems to have fixed that particular (chown error) issue.

However, the original issue that the signs don't have the text in them persists...

I think I ran into the block-not-mining issue that @compX44 mentioned:
> Also, I tried to destroy the item blocks that I put down, but they don't disappear. I keep on hitting the item and they make the sounds that means that they've been destroyed, but they don't disappear.

This happens when I try to mine blocks (sand or whatever) in a zone a few (10ish?) blocks around the spawn point. In this zone I also can't place signs. Try to move 20-odd blocks away from spawn point before starting to play with the signs.

**Comment by ulrikpedersen** [comment] 2023-03-13 22:43
😃 AHA! Just in that one last attempt before I pass out tonight - I think I got it! 🎉 

I stopped the server, went into `ops.json` and removed the user that was there and added my own. Then restarted the server with `mciwb start` connect client and shell and voila: signs now have the default text in them and works just like the video! 

So it seems you have to have operator permissions for this to work (seamlessly)

**Comment by compX44** [comment] 2023-03-13 23:51
I'm on Windows 10, using Ubuntu with the WSL extension in Vscode with the docker container. I have Python 3.10 and IPython 8.10.0. I'm using the latest version of Minecraft (1.19.3). I have updated to the latest mciwb package.


I tried the command and got the following output:

n [1]: world.signs.give_signs()

In [2]: world.player.inventory
Out[2]: 'Pyr0Blue has the following entity data: [{Slot: 0b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"select"}\'}, display: {Name: \'{"text":"select"}\'}}}, {Slot: 1b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"paste"}\'}, display: {Name: \'{"text":"paste"}\'}}}, {Slot: 2b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"expand"}\'}, display: {Name: \'{"text":"expand"}\'}}}, {Slot: 3b, id: "minecraft:oak_sign", Count: 1b, tag: {BlockEntityTag: {Text1: \'{"text":"clear"}\'}, display: {Name: \'{"text":"clear"}\'}}}]'


I went and removed the user in the ops.json file and replaced it with my own like @ulrikpedersen did and still couldn't get the same results as the demo video.

**Comment by compX44** [comment] 2023-03-14 00:00
I moved away from the spawn point as @ulrikpedersen suggested and had luck with the signs and mining there. I had to type on the signs though.

**Comment by gilesknap** [comment] 2023-03-14 06:20
@ulrikpedersen that was a good experiment to do. It's odd since the python code uses rcon and should not be user related. 

You are dead right about spawn protection. This stops anything building near to the spawn point. I thought I had that switched off.

@compX44 your inventory does indeed contains signs with the correct tags (name and Text1) so they should be working 
I'll do some more digging.

Thanks for all the useful feedback. I'll do more investigation after work this evening.

**Comment by gilesknap** [comment] 2023-03-14 06:23
> > In the game type /clear to remove all items from inventory.
> 
> This just gives me an error 

That's because you were not an operator - I should have thought of that. Although I did not think you need to be an operator to use mciwb it certainly helps for this kind of thing.

**Comment by gilesknap** [comment] 2023-03-14 07:13
@ulrikpedersen @compX44 I've just tried remvoing myself from ops and I can reproduce the blank sign issue.

So it seems like Ulrik has cracked it. Thanks!

I'll make an update to auto add you to ops when running `mciwb shell --user XXX` Note that being ops would also override spawn protection so this should fix everything.

Expect an update this evening.

**Comment by gilesknap** [comment] 2023-03-14 17:04
OK I think #82 has fixed the issue.

I've tried it out on WSL2 as well and all seems well.

The new version 0.8.5 is released with this fix. Let me know if it works for you.

To properly test this you will want to delete your existing server before starting a new one
```
mciwb stop
rm -r $HOME/mciwb-server
mciwb start
```

But having said that, this should work against an existing server if you have made changes you want to keep.


@ulrikpedersen @compX44 thanks for your help with this. It's the kind of error that I would never notice with self testing only.

**Comment by compX44** [comment] 2023-03-15 04:24
@gilesknap I stopped the server and restarted it after updating the mciwb and I was able to achieve the same results as the demo video. Thank you so much for looking into this.

**Comment by gilesknap** [comment] 2023-03-15 06:43
Awesome. Thanks for letting me know @compX44. Closing.

**Closed by gilesknap** 2023-03-15 06:43 UTC

**Comment by gilesknap** [comment] 2023-03-15 14:37
@compX44 @ulrikpedersen 

Slightly cheeky request here. I'm having another go at promoting this project today.
It would be nice to get a bit of a community going.

Maybe you would like to star this github repo? and or upvote this reddit 
https://www.reddit.com/r/Minecraftbuilds/comments/11rqauh/build_things_using_python/?utm_source=share&utm_medium=web2x&context=3

**Comment by ulrikpedersen** [comment] 2023-03-15 18:15
Checked now and it works out of the box for me too now 👍 

⭐ ✔️ 💯

**Comment by compX44** [comment] 2023-03-16 17:58
I don't have a reddit account, but I did see your project there while I was looking something up. Having a community would be nice.
